version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: monthly
      day: monday
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 3
    groups:
      patch:
        applies-to: version-updates
        update-types:
          - patch
          - minor

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 3